// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Polly_C.Horizon.Data.Polly_C.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Polly_C.Horizon.Data.Polly_C.Models
{
    public partial interface IPolly_CContextProcedures
    {
        Task<List<spDALC_Payment_FreqSelectResult>> spDALC_Payment_FreqSelectAsync(short? Payment_Freq_CD, string Short_Desc, int? Disp_Seq, DateTime? Eff_Date, DateTime? Exp_Date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spDALC_SmokerSelectResult>> spDALC_SmokerSelectAsync(byte? Smoker_CD, string S_Desc, short? Disp_Seq, DateTime? Eff_Date, DateTime? Exp_Date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetBeneficiaryDetailsResult>> spGetBeneficiaryDetailsAsync(int? PolicyNO, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetBenefitExtendedMemberDetailsResult>> spGetBenefitExtendedMemberDetailsAsync(int? PolicyNO, DateTime? EffectiveDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spGetPolicyAndMainMemberDetailsResult>> spGetPolicyAndMainMemberDetailsAsync(int? PolicyNo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spNewBusinessProcessResult>> spNewBusinessProcessAsync(string Source, Guid? MessageID, int? StatusCD, string SalesDivision, string AgentName, string AgentCode, string LegacyPolNo, DateTime? CaptureDate, DateTime? NewInceptDate, string MasterProductCode, string ProductCode, decimal? PolicyPremium, int? PartnerCD, string SchemeCD, int? DebitDay, string BankName, string BranchName, string BranchCode, string AccountNumber, int? PaymentTypeID, int? BankAccTypeCD, string AccountHolder, DateTime? EffectiveDate, DataTable Entity, DataTable Benefit, DataTable MemberAddr, DataTable MemberContact, OutputParameter<string> OutputMessage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
