// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Polly_C.Horizon.Data.Polly_C.Models
{
    public partial class spDALC_SmokerSelectResult
    {
        public byte Smoker_CD { get; set; }
        public string S_Desc { get; set; }
        public short Disp_Seq { get; set; }
        public DateTime Eff_Date { get; set; }
        public DateTime Exp_Date { get; set; }
    }
}
