// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Polly_C.Horizon.Data.Polly_C.Models
{
    public partial class spDALC_Payment_FreqSelectResult
    {
        public short Payment_Freq_CD { get; set; }
        public string Short_Desc { get; set; }
        public int? Disp_Seq { get; set; }
        public DateTime Eff_Date { get; set; }
        public DateTime Exp_Date { get; set; }
    }
}
