// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Polly_C.Horizon.Data.Polly_C.Models
{
    public partial class spGetBenefitExtendedMemberDetailsResult
    {
        public int Benefit { get; set; }
        public string BenefitDesctiption { get; set; }
        public DateTime DOC { get; set; }
        public decimal Premium { get; set; }
        [Column("Sum Assured")]
        public string SumAssured { get; set; }
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string Relation { get; set; }
        public string IDNumber { get; set; }
        public decimal? CoveredAmount { get; set; }
        public decimal? PremiumAmount { get; set; }
        public string WaitingPeriod { get; set; }
        public DateTime? DOB { get; set; }
        public string STATUS { get; set; }
    }
}
