// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Polly_C.Horizon.Data.Polly_C.Models
{
    public partial class spGetBeneficiaryDetailsResult
    {
        public string FirstName { get; set; }
        public string SurName { get; set; }
        public string Relation { get; set; }
        public string IDNumber { get; set; }
        public int? CoveredAmount { get; set; }
        public decimal? Allocation { get; set; }
        public int? DateCeded { get; set; }
        public DateTime? DOB { get; set; }
        public string STATUS { get; set; }
    }
}
