// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Polly_C.Horizon.Data.Polly_C.Models
{
    public partial class spNewBusinessProcessResult
    {
    }
}
