// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Polly_C.Horizon.Data.Customer.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Polly_C.Horizon.Data.Customer.Models
{
    public partial interface ICustomerContextProcedures
    {
        Task<List<spAdvancedPersonSearchResult>> spAdvancedPersonSearchAsync(string encashmentNo, string busRegNo, string appFormNo, string emailAddress, string businessName, string fullName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spCustomerPolicyInfoResult>> spCustomerPolicyInfoAsync(string EntityNo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spDALBankAccTypeSelectResult>> spDALBankAccTypeSelectAsync(byte? BankAccTypeCD, string BankAccTypeDesc, string BankAccTypeRegEx, short? DispSeq, bool? IsActive, DateTime? LastChanged, string UserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spDALBankSelectResult>> spDALBankSelectAsync(int? BankID, string BankName, string BankShortName, short? DispSeq, bool? IsActive, DateTime? LastChanged, string UserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spDALGenderSelectResult>> spDALGenderSelectAsync(byte? Gender_CD, string S_Desc, short? Disp_Seq, DateTime? Eff_Date, DateTime? Exp_Date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> spDALTelecomTypeSelectAsync(int? TelTypeCD, string CountryCode, string TelTypeCode, string TelTypeDesc, string TelTypeRegEx, short? DispSeq, bool? IsActive, DateTime? LastChanged, string UserID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spDALTitleSelectResult>> spDALTitleSelectAsync(int? Title_CD, string S_Desc, short? Disp_Seq, DateTime? Eff_Date, DateTime? Exp_Date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spPersonSearchResult>> spPersonSearchAsync(string policyNo, string legPolNo, string IFANo, string clientEntityNo, string legalRefNo, string cellNo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
