// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Polly_C.Horizon.Data.Customer.Models
{
    public partial class spCustomerPolicyInfoResult
    {
        public int PolicyNo { get; set; }
        public int IFANo { get; set; }
        public string ProductDescr { get; set; }
        public string PolicyStatus { get; set; }
        public short StatusCd { get; set; }
        public DateTime DateOfCommencement { get; set; }
        public string Payer { get; set; }
        public decimal PolicyPremium { get; set; }
        public DateTime BilledTo { get; set; }
        public DateTime PaidTo { get; set; }
        public int? PremiumCount { get; set; }
        public int PremiumFrequency { get; set; }
        public string SalesPerson { get; set; }
        public string DebiCheckStatus { get; set; }
        public string LegacyPolicyNo { get; set; }
        public DateTime StatusDate { get; set; }
    }
}
